//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspPoolCommunication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source={0};Persist Security Info=False;")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DbPath {
            get {
                return ((string)(this["DbPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM ssd WHERE number = @id")]
        public string FetchByIdQuery {
            get {
                return ((string)(this["FetchByIdQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM ssd WHERE Linia = @linija AND Kel = @kelias AND kilomrtras = @km AN" +
            "D piket = @pk AND metras = @m AND siule = @siule AND [saliginis kodas] IN (\'06.4" +
            "\', \'06.3\');")]
        public string FetchByVietaQuery {
            get {
                return ((string)(this["FetchByVietaQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"INSERT INTO ssd (Linia, Kel, kilomrtras, piket, metras, siule, [saliginis kodas], suv_numer, suvirino, IFas, Pak_suv_data, I_pat_data, I_pat_aparat, I_pat_operator, Pastaba) VALUES (@linija, @kelias, @km, @pk, @m, @siule, @skodas, @suv_numer, @suvirino, @ifas, @pak_suv_data, @data, @aparatas, @operatorius, @pastaba)")]
        public string InsertQuery {
            get {
                return ((string)(this["InsertQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string Ifas {
            get {
                return ((string)(this["Ifas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE ssd SET Pastaba = Pastaba + \" \" + @pastaba WHERE number = @id;")]
        public string UpdateExtraQuery {
            get {
                return ((string)(this["UpdateExtraQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE ssd SET {0} = @data, {1} = @aparatas, {2} = @operatorius, Pastaba = @pasta" +
            "ba WHERE number = @id")]
        public string UpdateQueryFormat {
            get {
                return ((string)(this["UpdateQueryFormat"]));
            }
        }
    }
}
