//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbMappings.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\r\n  {\r\n    \"name\": \"id\",\r\n    \"dbname\": \"number\",\r\n    \"typename\": \"System.Int64" +
            "\"\r\n  },\r\n  {\r\n    \"name\": \"linija\",\r\n    \"dbname\": \"Linia\",\r\n    \"typename\": \"Sy" +
            "stem.String\"\r\n  },\r\n  {\r\n    \"name\": \"kelias\",\r\n    \"dbname\": \"Kel\",\r\n    \"typen" +
            "ame\": \"System.Int32\"\r\n  },\r\n  {\r\n    \"name\": \"km\",\r\n    \"dbname\": \"kilomrtras\",\r" +
            "\n    \"typename\": \"System.Int32\"\r\n  },\r\n  {\r\n    \"name\": \"pk\",\r\n    \"dbname\": \"pi" +
            "ket\",\r\n    \"typename\": \"System.Int32\"\r\n  },\r\n  {\r\n    \"name\": \"m\",\r\n    \"dbname\"" +
            ": \"metras\",\r\n    \"typename\": \"System.Int32\"\r\n  },\r\n  {\r\n    \"name\": \"siule\",\r\n  " +
            "  \"dbname\": \"siule\",\r\n    \"typename\": \"System.Int32\"\r\n  },\r\n  {\r\n    \"name\": \"sk" +
            "odas\",\r\n    \"dbname\": \"saliginis kodas\",\r\n    \"typename\": \"System.String\"\r\n  },\r" +
            "\n  {\r\n    \"name\": \"suv_numer\",\r\n    \"dbname\": \"suv_numer\",\r\n    \"typename\": \"Sys" +
            "tem.Int32\"\r\n  },\r\n  {\r\n    \"name\": \"suvirino\",\r\n    \"dbname\": \"suvirino\",\r\n    \"" +
            "typename\": \"System.String\"\r\n  },\r\n  {\r\n    \"name\": \"nr_pagal_schema\",\r\n    \"dbna" +
            "me\": \"nr_pagal_shema\",\r\n    \"typename\": \"System.Int32\"\r\n  },\r\n  {\r\n    \"name\": \"" +
            "ifas\",\r\n    \"dbname\": \"IFas\",\r\n    \"typename\": \"System.Int32\"\r\n  },\r\n  {\r\n    \"n" +
            "ame\": \"pak_suv_data\",\r\n    \"dbname\": \"Pak_suv_data\",\r\n    \"typename\": \"System.Da" +
            "teTime\"\r\n  },\r\n  {\r\n    \"name\": \"data1\",\r\n    \"dbname\": \"I_pat_data\",\r\n    \"type" +
            "name\": \"System.DateTime\"\r\n  },\r\n  {\r\n    \"name\": \"aparatas1\",\r\n    \"dbname\": \"I_" +
            "pat_aparat\",\r\n    \"typename\": \"System.String\"\r\n  },\r\n  {\r\n    \"name\": \"operatori" +
            "us1\",\r\n    \"dbname\": \"I_pat_operator\",\r\n    \"typename\": \"System.String\"\r\n  },\r\n " +
            " {\r\n    \"name\": \"data2\",\r\n    \"dbname\": \"II_pat_data\",\r\n    \"typename\": \"System." +
            "DateTime\"\r\n  },\r\n  {\r\n    \"name\": \"aparatas2\",\r\n    \"dbname\": \"II_pat_aparat\",\r\n" +
            "    \"typename\": \"System.String\"\r\n  },\r\n  {\r\n    \"name\": \"operatorius2\",\r\n    \"db" +
            "name\": \"II_pat_operator\",\r\n    \"typename\": \"System.String\"\r\n  },\r\n  {\r\n    \"name" +
            "\": \"data3\",\r\n    \"dbname\": \"III_pat_data\",\r\n    \"typename\": \"System.DateTime\"\r\n " +
            " },\r\n  {\r\n    \"name\": \"aparatas3\",\r\n    \"dbname\": \"III_pat_aparat\",\r\n    \"typena" +
            "me\": \"System.String\"\r\n  },\r\n  {\r\n    \"name\": \"operatorius3\",\r\n    \"dbname\": \"III" +
            "_pat_operaqtor\",\r\n    \"typename\": \"System.String\"\r\n  },\r\n  {\r\n    \"name\": \"data4" +
            "\",\r\n    \"dbname\": \"IV_pat_data\",\r\n    \"typename\": \"System.DateTime\"\r\n  },\r\n  {\r\n" +
            "    \"name\": \"aparatas4\",\r\n    \"dbname\": \"IV_pat_aparat\",\r\n    \"typename\": \"Syste" +
            "m.String\"\r\n  },\r\n  {\r\n    \"name\": \"operatorius4\",\r\n    \"dbname\": \"IV_pat_operato" +
            "r\",\r\n    \"typename\": \"System.String\"\r\n  },\r\n  {\r\n    \"name\": \"pastaba\",\r\n    \"db" +
            "name\": \"Pastaba\",\r\n    \"typename\": \"System.String\"\r\n  },\r\n  {\r\n    \"name\": \"pana" +
            "ikintas\",\r\n    \"dbname\": \"Panaikintas\",\r\n    \"typename\": \"System.Boolean\"\r\n  },\r" +
            "\n  {\r\n    \"name\": \"defekto_id\",\r\n    \"dbname\": \"DefektoId\",\r\n    \"typename\": \"Sy" +
            "stem.Int64\"\r\n  }\r\n]")]
        public string JsonString {
            get {
                return ((string)(this["JsonString"]));
            }
        }
    }
}
