//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Widm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class RecValidation : global::System.Configuration.ApplicationSettingsBase {
        
        private static RecValidation defaultInstance = ((RecValidation)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RecValidation())));
        
        public static RecValidation Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckIfDateIfReal {
            get {
                return ((bool)(this["CheckIfDateIfReal"]));
            }
            set {
                this["CheckIfDateIfReal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int AllowedDaysInPast {
            get {
                return ((int)(this["AllowedDaysInPast"]));
            }
            set {
                this["AllowedDaysInPast"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06.4, 06.3")]
        public string SalygKodai {
            get {
                return ((string)(this["SalygKodai"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("807, 806, 830, 831")]
        public string Aparatai {
            get {
                return ((string)(this["Aparatai"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IF4, IF3, GTC, VitrasS, gamykla")]
        public string Suvirino {
            get {
                return ((string)(this["Suvirino"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1, 2, 3, 4, papild")]
        public string Kelinti {
            get {
                return ((string)(this["Kelinti"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01, 17, 22, 23, 24, 46, 47, 48, 49, 50, 51, 52, 86, 87, 94, 95, 96 ")]
        public string Linijos {
            get {
                return ((string)(this["Linijos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D3, D2, D1, DP, ID, L")]
        public string Pavojingumai {
            get {
                return ((string)(this["Pavojingumai"]));
            }
        }
    }
}
